name: CMake Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qtbase5-dev libboost-test-dev cmake g++

    - name: Configure CMake
      run: cmake -B build -S .

    - name: Build
      run: cmake --build build

    - name: Run Unit Tests
      run: ./build/artemis_tests
